options:
  env:
    - "GOPATH=/go"
  volumes:
    - name: go-modules-pkg
      path: /go/pkg
    - name: go-modules-bin
      path: /go/bin
    - name: go-modules-src
      path: /go/src
  machineType: 'E2_HIGHCPU_8'
steps:
  - id: go_version
    name: "gcr.io/cloud-builders/go:debian"
    args: [ "version" ]

  - id: go_test
    name: "gcr.io/cloud-builders/go"
    args: ["test","./..."]

timeout: 1800s
logsBucket: '${_CLOUD_BUILD_STORAGE_BUCKET}'
