options:
  env:
    - "GOPATH=/go"
    - "BRANCH_NAME=${BRANCH_NAME}"
    - "COMMIT_SHA=${COMMIT_SHA}"
    - "PROJECT_ID=${PROJECT_ID}"
    - "CODECOV_TOKEN=ce852600-2555-4fe4-8c9f-4129b6884883"
  volumes:
    - name: go-modules-pkg
      path: /go/pkg
    - name: go-modules-bin
      path: /go/bin
    - name: go-modules-src
      path: /go/src
  machineType: 'E2_HIGHCPU_8'
steps:
  # See https://www.npmjs.com/package/editorconfig-checker
  # The .editorconfig file enforces formatting standards such as whether indents
  # should be tabs or spaces. Editors like VSCode will read the file and behave
  # according to the formatting defined in this file.
  - id: eclint
    name: "e53e225/editorconfig-checker"

  - id: go_version
    name: "gcr.io/cloud-builders/go:debian"
    args: [ "version" ]

  - id: go_linter
    name: "golangci/golangci-lint"
    args: ["golangci-lint", "run", "-v", "--build-tags", "test"]

  - id: go_test
    name: "gcr.io/$PROJECT_ID/cloud-builders/tests-with-codecov"

  - id: go_security
    name: "securego/gosec"
    args: [ "./..." ]

timeout: 1800s
logsBucket: '${_CLOUD_BUILD_STORAGE_BUCKET}'
