options:
  env:
    - "GOPATH=/go"
    - "BRANCH_NAME=${BRANCH_NAME}"
    - "PROJECT_ID=${PROJECT_ID}"
  volumes:
    - name: go-modules-pkg
      path: /go/pkg
    - name: go-modules-bin
      path: /go/bin
    - name: go-modules-src
      path: /go/src
  machineType: 'E2_HIGHCPU_8'
substitutions:
  _FLEXIBLE_SERVICE: flexible-service
  _GCR_REPO_ENDPOINT: eu.gcr.io/sk-borislav
  _VULNZ_CHECK_POLICY: .cloudbuild/docker/vulnerability_scan_policy.yaml
steps:
  # See https://www.npmjs.com/package/editorconfig-checker
  # The .editorconfig file enforces formatting standards such as whether indents
  # should be tabs or spaces. Editors like VSCode will read the file and behave
  # according to the formatting defined in this file.
  - id: eclint
    name: "e53e225/editorconfig-checker"

  - id: go_version
    name: "gcr.io/cloud-builders/go:debian"
    args: [ "version" ]

  - id: go_linter
    name: "golangci/golangci-lint"
    args: ["golangci-lint", "run", "-v", "--build-tags", "test"]

  - id: go_test
    name: "golang:1.19"
    args: ["go", "test", "./..."]

  - id: go_security
    name: "securego/gosec"
    args: [ "./..." ]

  - id: build_flexible_service
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -ce
      - |
        docker build -t ${_GCR_REPO_ENDPOINT}/${_FLEXIBLE_SERVICE} -f Dockerfile .

  - id: push_flexible_service
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -ce
      - |
        docker push ${_GCR_REPO_ENDPOINT}/${_FLEXIBLE_SERVICE}
        docker image inspect ${_GCR_REPO_ENDPOINT}/${_FLEXIBLE_SERVICE} --format '{{index .RepoDigests 0}}' > ${_FLEXIBLE_SERVICE}-image-digest.txt
        cat ${_FLEXIBLE_SERVICE}-image-digest.txt

  - id: sign_flexible_service
    name: 'gcr.io/$PROJECT_ID/cloud-builders/ci-image-signer'
    env:
      - "DIGEST_FILENAME=${_FLEXIBLE_SERVICE}-image-digest.txt"
      - "VULNZ_CHECK_POLICY=${_VULNZ_CHECK_POLICY}"
      - "KMS_DIGEST_ALGORITHM=${_KMS_DIGEST_ALGORITHM}"
      - "KMS_KEY_NAME=${_KMS_KEY_NAME}"
      - "ATTESTOR_NAME=${_ATTESTOR_NAME}"

  - id: deploy_service
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - -ce
      - |
        gcloud config set app/cloud_build_timeout 1600 
        gcloud app deploy --image-url=${_GCR_REPO_ENDPOINT}/${_FLEXIBLE_SERVICE} --appyaml=services/app-ae-flexible/app.yaml

timeout: 1800s
logsBucket: '${_CLOUD_BUILD_STORAGE_BUCKET}'
